{
 "title": "Pita Serverless CockroachDB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pitas!",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "\n<div style=\"text-align: center;\">\n<img src=\"https://storage.googleapis.com/thegym-public/pita1980.png\" style=\"text-align: center; width: 50%;\"></img>\n</div>"
   }
  },
  {
   "title": " Appserver & db availability",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sql_isup{app=\"pita\", component=\"appserver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"pita\", component=\"appserver\"} or vector(0))/  sum(process_start_time_seconds{app=\"pita\", component=\"appserver\"} or vector(1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of pitas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "Select count(*) from Pita;" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Pita Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(distinct createdby) from Pita;"
    }
   ]
  },
  {
   "title": "SQL Queries ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sql_selects_count", "legendFormat": "SELECT" },
    { "expr": "sql_inserts_count", "legendFormat": "INSERT" },
    { "expr": "sql_updates_count", "legendFormat": "UPDATE" },
    { "expr": "sql_deletes_count", "legendFormat": "DELETE" },
    { "expr": "sql_creates_count", "legendFormat": "CREATE" }
   ]
  },
  {
   "title": "Transactions ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sql_transactions_count", "legendFormat": "BEGIN" },
    { "expr": "sql_commits_count", "legendFormat": "COMMIT" },
    { "expr": "sql_rollbacks_count", "legendFormat": "ROLLBACK" }
   ]
  },
  {
   "title": "HTTP errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "http_request_duration_ms_count{status=~\"[45].*\"}",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "http_request_duration_ms_count", "legendFormat": "{{route}}, {{status}}" }
   ]
  },
  {
   "title": "Average duration in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"pita\"}[5m])/ ((irate(http_request_duration_ms_count{app=\"pita\"} [5m]))))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{app=\"pita\"} |= ``"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"pita\"}  |= `rror`"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "filters": [
      {
       "id": "b44afd39",
       "operator": "=",
       "scope": "span",
       "tag": "http.host",
       "value": [ "app" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "pita" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "0",
       "valueType": "duration"
      },
      {
       "id": "span-name",
       "operator": "!~",
       "scope": "span",
       "tag": "name",
       "value": [ "GET /sleep" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}